version: '3.8'
services:
  backend :
    build : .
    container_name: backend
    ports:
      - "8080:8080"

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: techtalk
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379

volumes:
  mysql-data:
  mongo:
